// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("WebApp.Models.CommandDefinition", b =>
                {
                    b.Property<byte>("CommandCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeprecationMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("ExpectedResponseCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FirmwareVersionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("CommandCode");

                    b.HasIndex("FirmwareVersionId");

                    b.ToTable("CommandDefinitions");
                });

            modelBuilder.Entity("WebApp.Models.Feature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FeatureCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsComposite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("RequiredLpiParams")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("RequiredPiccoloCommands")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeatureCollectionId");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("WebApp.Models.FeatureCollection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LockedReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NpiProgramId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequiredLpiVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequiredPiccoloVersionId")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("SharedWith")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Visibility")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NpiProgramId");

                    b.HasIndex("RequiredLpiVersionId");

                    b.HasIndex("RequiredPiccoloVersionId");

                    b.ToTable("FeatureCollections");
                });

            modelBuilder.Entity("WebApp.Models.FirmwareVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ChangeLog")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NpiProgramId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleasedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Stage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NpiProgramId");

                    b.ToTable("FirmwareVersions");
                });

            modelBuilder.Entity("WebApp.Models.NpiProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HardwareGen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PmoOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProgramStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NpiPrograms");
                });

            modelBuilder.Entity("WebApp.Models.OperationalFlow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FeatureId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OperationalFlows");
                });

            modelBuilder.Entity("WebApp.Models.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte?>("CommandDefinitionCommandCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeprecationMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FirmwareVersionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxValue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommandDefinitionCommandCode");

                    b.HasIndex("FirmwareVersionId");

                    b.ToTable("ParameterDefinitions");
                });

            modelBuilder.Entity("WebApp.Models.CommandDefinition", b =>
                {
                    b.HasOne("WebApp.Models.FirmwareVersion", null)
                        .WithMany("Commands")
                        .HasForeignKey("FirmwareVersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApp.Models.Feature", b =>
                {
                    b.HasOne("WebApp.Models.FeatureCollection", null)
                        .WithMany("Features")
                        .HasForeignKey("FeatureCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("WebApp.Models.ParameterValue", "Parameters", b1 =>
                        {
                            b1.Property<Guid>("FeatureId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("ParameterId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ParameterName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FeatureId", "Id");

                            b1.ToTable("ParameterValue");

                            b1.WithOwner()
                                .HasForeignKey("FeatureId");
                        });

                    b.OwnsMany("WebApp.Models.PiccoloCommand", "Commands", b1 =>
                        {
                            b1.Property<Guid>("FeatureId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<byte>("CommandCode")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CommandName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<int>("ExecutionOrder")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.PrimitiveCollection<string>("Payload")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("FeatureId", "Id");

                            b1.ToTable("PiccoloCommand");

                            b1.WithOwner()
                                .HasForeignKey("FeatureId");
                        });

                    b.Navigation("Commands");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("WebApp.Models.FeatureCollection", b =>
                {
                    b.HasOne("WebApp.Models.NpiProgram", "TargetProgram")
                        .WithMany()
                        .HasForeignKey("NpiProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Models.FirmwareVersion", "RequiredLpiVersion")
                        .WithMany()
                        .HasForeignKey("RequiredLpiVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.FirmwareVersion", "RequiredPiccoloVersion")
                        .WithMany()
                        .HasForeignKey("RequiredPiccoloVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequiredLpiVersion");

                    b.Navigation("RequiredPiccoloVersion");

                    b.Navigation("TargetProgram");
                });

            modelBuilder.Entity("WebApp.Models.FirmwareVersion", b =>
                {
                    b.HasOne("WebApp.Models.NpiProgram", "NpiProgram")
                        .WithMany("FirmwareVersions")
                        .HasForeignKey("NpiProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NpiProgram");
                });

            modelBuilder.Entity("WebApp.Models.OperationalFlow", b =>
                {
                    b.OwnsMany("WebApp.Models.FlowOperation", "Operations", b1 =>
                        {
                            b1.Property<Guid>("OperationalFlowId")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("OperationalFlowId", "Id");

                            b1.ToTable("FlowOperation");

                            b1.WithOwner()
                                .HasForeignKey("OperationalFlowId");

                            b1.OwnsMany("WebApp.Models.FlowStep", "Steps", b2 =>
                                {
                                    b2.Property<Guid>("FlowOperationOperationalFlowId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("FlowOperationId")
                                        .HasColumnType("TEXT");

                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("AttributesJson")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("Attributes");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("StepNumber")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Title")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("FlowOperationOperationalFlowId", "FlowOperationId", "Id");

                                    b2.ToTable("FlowStep");

                                    b2.WithOwner()
                                        .HasForeignKey("FlowOperationOperationalFlowId", "FlowOperationId");

                                    b2.OwnsMany("WebApp.Models.FlowBranch", "Branches", b3 =>
                                        {
                                            b3.Property<Guid>("FlowStepFlowOperationOperationalFlowId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("FlowStepFlowOperationId")
                                                .HasColumnType("TEXT");

                                            b3.Property<Guid>("FlowStepId")
                                                .HasColumnType("TEXT");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("Action")
                                                .IsRequired()
                                                .HasColumnType("TEXT");

                                            b3.Property<string>("Description")
                                                .IsRequired()
                                                .HasColumnType("TEXT");

                                            b3.Property<bool>("IsErrorPath")
                                                .HasColumnType("INTEGER");

                                            b3.Property<string>("Label")
                                                .IsRequired()
                                                .HasColumnType("TEXT");

                                            b3.HasKey("FlowStepFlowOperationOperationalFlowId", "FlowStepFlowOperationId", "FlowStepId", "Id");

                                            b3.ToTable("FlowBranch");

                                            b3.WithOwner()
                                                .HasForeignKey("FlowStepFlowOperationOperationalFlowId", "FlowStepFlowOperationId", "FlowStepId");
                                        });

                                    b2.Navigation("Branches");
                                });

                            b1.Navigation("Steps");
                        });

                    b.Navigation("Operations");
                });

            modelBuilder.Entity("WebApp.Models.ParameterDefinition", b =>
                {
                    b.HasOne("WebApp.Models.CommandDefinition", null)
                        .WithMany("Parameters")
                        .HasForeignKey("CommandDefinitionCommandCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("WebApp.Models.FirmwareVersion", null)
                        .WithMany("Parameters")
                        .HasForeignKey("FirmwareVersionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApp.Models.CommandDefinition", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("WebApp.Models.FeatureCollection", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("WebApp.Models.FirmwareVersion", b =>
                {
                    b.Navigation("Commands");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("WebApp.Models.NpiProgram", b =>
                {
                    b.Navigation("FirmwareVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
